# Generated by Django 4.2.6 on 2023-10-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_index', models.PositiveSmallIntegerField(unique=True)),
                ('floor_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.PositiveIntegerField(blank=True, null=True)),
                ('end_x', models.PositiveIntegerField(blank=True, null=True)),
                ('start_y', models.PositiveIntegerField(blank=True, null=True)),
                ('end_y', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('E', 'Empty'), ('B', 'Booked'), ('U', 'Used')], default='E', max_length=1)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingfloor')),
            ],
        ),
    ]
