# Generated by Django 4.2.6 on 2023-10-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingfloor',
            name='floor_index',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='end_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='end_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='start_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='start_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
