# Generated by Django 4.2.6 on 2023-10-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingfloor_floor_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='floor_id',
            new_name='floor',
        ),
    ]
