# Generated by Django 4.2.6 on 2023-10-28 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0004_vehicletype_registeredvehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredVehicle',
            new_name='Vehicle',
        ),
    ]
