# Generated by Django 4.2.6 on 2023-10-29 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0005_rename_registeredvehicle_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('VCB', 'Vietcombank'), ('MB', 'MB Bank')], max_length=5)),
                ('account_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_booked', models.DateTimeField(default=datetime.datetime(2023, 10, 29, 10, 2, 0, 97715, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('A', 'Available'), ('E', 'Expired'), ('C', 'Checked-in')], default='A', max_length=1)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_out', models.DateTimeField(blank=True, default=None, null=True)),
                ('fee', models.FloatField(blank=True, default=None, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.bankaccount')),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.checkin')),
            ],
        ),
    ]
