# Generated by Django 4.2.6 on 2023-11-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_bill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(choices=[('VCB', 'Vietcombank'), ('OCB', 'OCB')], max_length=5),
        ),
    ]
